fix lhm where code is pushing nulls to array of list
databricks-demos/dbdemos-notebooks pull request #34
Opened 2024-07-09 21:56 UTC by peterpark-db

There is a bug in the LHM demo where it pushes nulls to array of list, causing error:
```
Can not merge type `ArrayType` and `DoubleType`.
```

Also made few changes:
1. Uncomment SLICING_EXPRS
2. Check if drift table exists

2024-07-09 23:10 UTC, QuentinAmbard commented on product_demos/DBSQL-Datawarehousing/lakehouse-monitor/01-Timeseries-monitor.py
> +while not spark.catalog.tableExists(drift_table) or spark.table(drift_table).isEmpty():
can you do it in a range to make sure it doesn't loop forever?

2024-07-09 23:11 UTC, QuentinAmbard commented
@aelhelouDB could you help reviewing this PR ?

2024-07-10 15:56 UTC, aelhelouDB requested changes
- Use monitor API to check if monitor/refresh has finished (instead of verifying if drift table exists... because it can exist anyway but without being refreshed)
- Accept proposed work-around to mitigate type-merge issue but keep a TODO to make it more robust/consistent later

2024-07-10 15:56 UTC, aelhelouDB commented on product_demos/DBSQL-Datawarehousing/lakehouse-monitor/01-Timeseries-monitor.py
> +while not spark.catalog.tableExists(drift_table) or spark.table(drift_table).isEmpty():
Can we use the API's method to check if monitor and refresh has finished:
```suggestion
import time
from databricks.sdk.service.catalog import MonitorInfoStatus, MonitorRefreshInfoState


# Wait for monitor to be created
while info.status == MonitorInfoStatus.MONITOR_STATUS_PENDING::
  info = w.quality_monitors.get(table_name=f"{catalog}.{dbName}.{TABLE_NAME}")
  time.sleep(10)

assert info.status == MonitorInfoStatus.MONITOR_STATUS_ACTIVE, "Error creating monitor"

refreshes = w.quality_monitors.list_refreshes(table_name=f"{catalog}.{dbName}.{TABLE_NAME}").refreshes
assert(len(refreshes) > 0)

run_info = refreshes[0]
while run_info.state in (MonitorRefreshInfoState.PENDING, MonitorRefreshInfoState.RUNNING):
  run_info = w.quality_monitors.get_refresh(table_name=f"{catalog}.{dbName}.{TABLE_NAME}", refresh_id=run_info.refresh_id)
  time.sleep(30)

assert run_info.state == MonitorRefreshInfoState.SUCCESS, "Monitor refresh failed"
```

if too verbose then we can stick to just ensuring the refresh job has been completed

2024-07-10 15:56 UTC, aelhelouDB commented on product_demos/DBSQL-Datawarehousing/lakehouse-monitor/_resources/01-DataGeneration.py
> +        if column in ['ProductTags', 'Wishlist']:
@peterpark-db is this the workaround to fix the type merge issue ? @QuentinAmbard we can accept this for now as a temporary fix and see how we can re-write it in a more elegant and robust way later

2024-07-10 19:49 UTC, peterpark-db commented on product_demos/DBSQL-Datawarehousing/lakehouse-monitor/01-Timeseries-monitor.py
> +while not spark.catalog.tableExists(drift_table) or spark.table(drift_table).isEmpty():
Committed the suggestion but also removed the check for the profile table that was there before

2024-07-10 19:50 UTC, peterpark-db commented on product_demos/DBSQL-Datawarehousing/lakehouse-monitor/_resources/01-DataGeneration.py
> +        if column in ['ProductTags', 'Wishlist']:
Yes, this is the fix for the type merge

2024-07-22 09:40 UTC, merged